#!/bin/zsh

if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root" 1>&2
    exit 1
fi

make mrproper
make menuconfig
make dep
make clean
make bzImage
make modules
make modules_install
cp arch/i386/boot/bzImage /boot/
cp System.map /boot/
mkinitrd /boot/proj1 3.0.4
vim /boot/grub/grub.conf
